version: "3"
services:
    web:
      image: nginx
      ports:
        - "80:80"
    database:
      image: redis
    myapp:
      image: vijithak/myapp:1.0
      ports:
        - "8080:8080"